---
version: 2

updates:

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
