[tool.poetry]
name = "juliet"
version = "1.0.1"
description = "A simple IRC relay bot for radio networks."
authors = ["W0JHX <jheddings@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
pyserial = "^3.5"
pyyaml = "^6.0.1"
irc = "^20.3.0"

[tool.poetry.group.dev.dependencies]
GitPython = "^3.1.37"
pre-commit = "^3.4.0"
pytest = "^7.4.2"
coverage = "^7.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
