[project]
name = "juliet"
version = "1.0.1"
description = "A simple IRC relay bot for radio networks."
authors = [{ name = "W0JHX", email = "jheddings@gmail.com" }]
requires-python = ">=3.12, <4"
readme = "README.md"
license = "MIT"
dependencies = [
    "pyserial>=3.5,<4",
    "pyyaml>=6.0.3,<7",
    "irc>=20.5.0,<21",
]

[dependency-groups]
dev = [
    "GitPython>=3.1.46,<4",
    "pre-commit>=4.5.1,<5",
    "pytest>=9.0.3,<10",
    "coverage>=7.13.5,<8",
    "ruff>=0.15.11,<0.16",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["juliet"]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "I",   # isort
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "G",   # flake8-logging-format
    "RET", # flake8-return
    "N",   # pep8-naming
    "ERA", # eradicate
    "UP",  # pyupgrade
]
ignore = [
    "E501", # line-too-long
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["juliet"]
